### ISSUE TITLE
layan-cursor-theme-git does not exist in the xerolinux_repo

### ISSUE THREAD

**Issue by Miroxyz** [xerolinux/xero-layan-git#1]
```
Installing Layan Theme
#################################
error: target not found: layan-cursor-theme-git
```

**Comment by theCode-Breaker** [comment]
@Miroxyz If it is not available then just remove `layan-cursor-theme-git` from the Archinstall script and install it then go to settings>appearance>cursors>get new cursor and install the required cursor theme manually

**Comment by theCode-Breaker** [comment]
@TechXero pls see to this

**Comment by TechXero** [comment]
> layan-cursor-theme-git

Layan cursor is no longer being used will remove it from package

**Comment by theCode-Breaker** [comment]
Okay thanks

**Comment by TechXero** [comment]
> Okay thanks

Done removed
